runtime: python310

env_variables:
  PYTHONUNBUFFERED: 'True'

handlers:
- url: /.*
  script: auto

entrypoint: streamlit run app.py --server.port=$PORT --server.headless=true --server.enableCORS=false --server.enableXsrfProtection=false